CREATE LOGIN [SkateReportU]
    WITH PASSWORD = N'xipohlb7tqcuYdoiyhzmrab}msFT7_&#$!~<dq{gONlqy<zz', SID = 0xE02D71ADC7BB38499FE75F0EAA7853A3, DEFAULT_DATABASE = [SkateOne], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

