CREATE LOGIN [SkateU]
    WITH PASSWORD = N'xipoeVhlbtunmrdiyhzmmruamsFT7_&#$!~<QIzq{Iglytzz', SID = 0x3BD01247F7AAE54B9AAA9FE9E402B425, DEFAULT_DATABASE = [SkateOne], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

